server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: user-service-route
          uri: ${USER_SERVICE_URI:lb://USER-SERVICE}
          predicates:
            - Path=/api/v1/users/**
        - id: course-service-route
          uri: ${COURSE_SERVICE_URI:lb://COURSE-SERVICE}
          predicates:
            - Path=/api/v1/courses/**
        - id: media-service-route
          uri: ${MEDIA_SERVICE_URI:lb://MEDIA-SERVICE}
          predicates:
            - Path=/api/v1/media/**
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedOriginPatterns: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
  endpoint:
    gateway:
      enabled: true
